# Generated by Django 3.2 on 2021-05-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='bname',
            field=models.CharField(default='default name', max_length=500),
        ),
    ]
