# Generated by Django 3.2 on 2021-05-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0009_auto_20210528_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='alternateVendorCode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bundle',
            name='loiNumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='ringiNumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='testModel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='alternateVendor',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bundle',
            name='sourcingReason',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
