# Generated by Django 3.2 on 2021-05-17 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerCode', models.CharField(max_length=100)),
                ('itemCode', models.CharField(max_length=100)),
                ('itemName', models.CharField(max_length=500)),
                ('vendorCode', models.CharField(max_length=100)),
                ('vendorName', models.CharField(max_length=500)),
                ('currentBasicCost', models.FloatField()),
                ('currentSOB', models.FloatField()),
                ('approvalNumber', models.IntegerField(default=0)),
                ('approver1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals1', to=settings.AUTH_USER_MODEL)),
                ('approver2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals2', to=settings.AUTH_USER_MODEL)),
                ('approver3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals3', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
