# Generated by Django 3.2 on 2021-05-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='currentBasicCost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='currentSOB',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
