# Generated by Django 3.2 on 2021-05-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20210518_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='alternateVendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='sourcingReason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='underProcess',
            field=models.BooleanField(default=False),
        ),
    ]
