# Generated by Django 3.2 on 2021-05-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20210527_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='currentBasicCost',
            new_name='bomQty',
        ),
        migrations.AddField(
            model_name='part',
            name='dept',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='rootPart',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
