# Generated by Django 3.2 on 2021-05-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('completion', models.IntegerField(default=0, max_length=100)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='parts.part')),
            ],
        ),
    ]
