# Generated by Django 3.2 on 2021-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='completion',
            field=models.IntegerField(default=0),
        ),
    ]
