# Generated by Django 3.2 on 2021-05-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0001_initial'),
        ('timelines', '0002_alter_timeline_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='bundles.bundle'),
        ),
    ]
