# Generated by Django 3.2 on 2021-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_timeline_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='part',
        ),
        migrations.AddField(
            model_name='timeline',
            name='actualED',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='actualSD',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='endDate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='startDate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
