# Generated by Django 3.2 on 2021-05-27 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0009_auto_20210528_0036'),
        ('timelines', '0005_timeline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='bundle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='bundles.bundle'),
            preserve_default=False,
        ),
    ]
